### ISSUE TITLE
Dataset Annotation Doubt

### ISSUE THREAD

**Issue by hshreeshail** [chevalierNoir/OpenASL#2]
In Section 3, paragraph 3, the paper states "Each annotator views the video clip and is given the original English sentence from the subtitle for reference. The annotator marks the"
1. corrected beginning and end of the sentence.
2. and provides a corrected English translation if needed

Step-2 is clear to me.

I apologize but it was not clear to me in step-1 whether the annotator
- edits the video clip timestamps to match the sentence
OR
- edits the sentence (including/excluding words) to match what is signed in the video clip.

**Comment by chevalierNoir** [comment]
Mostly the second one. But the annotator can also adjust the timestamps (e.g., when a video clip is a partial sentence).
