### ISSUE TITLE
Visual Encoder Initialization during Pre-Training

### ISSUE THREAD

**Issue by hshreeshail** [chevalierNoir/OpenASL#3]
From Section A.7 of Appendix: When **pretraining** the visual encoder (I3D) model, what is the initialization of the model? 
Is it initialized randomly or is it initialized with parameters trained on some video classification dataset (the way AlexNet/Inception networks used in SLT are initialized with ImageNet trained parameters).

**Comment by chevalierNoir** [comment]
The I3D is pre-trained on Kinetics-400 (see paragraph "Visual Backbone" of section A.4)
